---
title: "Bootstrapping Regression Metrics"
author: "Your Name"
date: "`r format(Sys.time(), '%d %B, %Y')`"
html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

## Introduction

In this assignment we use bootstrapping to estimate the standard error 
of several regression coefficients. We did this in class with adjusted R-squared.

In the past few assignments I've created most of the framework for you and 
asked you to fill in pieces that I've left blank. This assignment is 
different. I'll ask you use techniques we've discussed to answer some questions
that I'll ask, but you'll be doing most of the coding and writing on your own. 
Feel free to use this actual RMD file for your writing, but now you'll need 
to know how to do code blocks and things like that. If you're anything like me,
you'll find the 
[R Markdown Cheat Sheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf)
invaluable. Please write this document with attention to things like headers, 
spelling, 
and formatting. It need not be as polished as a formal report, but 
I'll ask you to revise
it if it looks like garbage. I'm not expecting a ton of writing here, but I'd like 
it to look nice. Remember to knit your document to HTML and commit both 
your RMD and HTML files. 

## Assignment

Here is what I'd like you do: 

1. Begin by building a regression model using the satisfaction survey data. Have your 
model predict satisfaction as a function of tenure and assigned sex. This is the model
we built in class. 
1. Describe the results briefly. This means reporting the $R^2$, the residual standard
errors, the coefficients and their standard errors. This model 
should have four terms, with one each for the intercept and tenure and two for 
assigned sex. 
1. Use bootstrap resampling (either the `rsample` method or the manual method) to 
generate standard error estimates for the residual standard error and the model terms. 
Report the 90% confidence interval for these statistics from the bootstrap replicates. 
1. Briefly compare the values from `summary.lm` to the bootstrap replicates. 

As always, please me know if you have any questions. Feel free to ask on Teams 
so that your
classmates benefit from your curiosity or confusion. 






